// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bGch6tJbdrGi0Yog6pdWRADnMcfpf5s',
    appId: '1:631641346172:web:55242e76359fc435ebf9f9',
    messagingSenderId: '631641346172',
    projectId: 'skoro-17721',
    authDomain: 'skoro-17721.firebaseapp.com',
    storageBucket: 'skoro-17721.firebasestorage.app',
    measurementId: 'G-8B46JL8HDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeqI4w-JImk8QL16xlaLzaN8jAuQ3oZU',
    appId: '1:631641346172:android:3e06475b6424efa5ebf9f9',
    messagingSenderId: '631641346172',
    projectId: 'skoro-17721',
    storageBucket: 'skoro-17721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmv6LF9cLh3DmvIR6hnnx9uvN2xi6nryg',
    appId: '1:631641346172:ios:3c23738f809c30eaebf9f9',
    messagingSenderId: '631641346172',
    projectId: 'skoro-17721',
    storageBucket: 'skoro-17721.firebasestorage.app',
    iosBundleId: 'com.harikiruthik.skoro.skoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmv6LF9cLh3DmvIR6hnnx9uvN2xi6nryg',
    appId: '1:631641346172:ios:3c23738f809c30eaebf9f9',
    messagingSenderId: '631641346172',
    projectId: 'skoro-17721',
    storageBucket: 'skoro-17721.firebasestorage.app',
    iosBundleId: 'com.harikiruthik.skoro.skoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1bGch6tJbdrGi0Yog6pdWRADnMcfpf5s',
    appId: '1:631641346172:web:ad88dafd3dda4146ebf9f9',
    messagingSenderId: '631641346172',
    projectId: 'skoro-17721',
    authDomain: 'skoro-17721.firebaseapp.com',
    storageBucket: 'skoro-17721.firebasestorage.app',
    measurementId: 'G-FHK3GMD9XT',
  );
}
